---
title: "À propos"
toc: false
---

## 

## Quoi?

Dans le cadre du cours de FAS-1002, nous avons eu la mission de produire un rapport analytique qui est consultable à partir d'une page Web personalisée. Pour ce faire, nous avons mis en relation des données environnementales portant sur l'ensemble des pays depuis 1850 à partir des bases de données du site "Our World in Data".

## Qui?

Ce projet est réalisé en équipe de deux avec Philippe Rosa et Bertrand Turcotte en liant nos deux ordinateurs à travers la plateforme GitHub. L'application R et R studio ont également été utilisé pour coder le site web ainsi que pour produire l'analyse et le traitement des données.

## Contact

**Programme** \| [Microprogramme en analyse des mégadonnées en sciences humaines et sociales](https://admission.umontreal.ca/programmes/microprogramme-de-1er-cycle-en-analyse-des-megadonnees-en-sciences-humaines-et-sociales/structure-du-programme/)

**Université** \| [Université de Montréal](https://umontreal.ca)

**Courriel** \| bertrand.turcotte\@umontreal.ca et philippe.rosa\@umontreal.ca

## Remerciement

Nous tennons à remercier notre professeur Samuel Guay, doctorant en psychologie - option neuroscience cognitive, pour son aide dans la réalisation du site web.
