---
title: "Projet d'analyse visuelle sur l'évolution de la performance environnementale des continents depuis 1850"
title-block-banner: true
description: | 
  Ce projet est réalisé dans le cadre du cours de FAS 1002 - Initatiation à la programmation à l'Université de Montréal 
# à changer
date: "2022-12-21"
# Modifier les détails que vous voulez
author:
  - name: "Bertrand Turcotte et Philippe Rosa"
    # Votre site web perso ou github
    url: https://github.com/VOTREUSERNAME
    # les champs d'affiliation sont optionnels, vous pouvez les
    # comment out en ajoutant un # devant.
    affiliation: FAS1002
    affiliation-url: https://FAS1002.github.io/A22
    # changer pour votre propre orcid id
    # https://orcid.org/ pour vous inscrire.
    orcid: 0000-0000-0000-0000

# TRUE == Générer une citation pour cette page précise. Pour enlever, mettre false.
citation: false
# Inclure les références que vous utilisez dans vos rapports. Je conseille Zotero pour construire
# ce fichier ou de connecter RStudio directement pour pouvoir citer avec @nom-de-reference.
bibliography: references.bib
---

Ce projet d'analyse utilise les bases de données environnementales de "World in Data" afin de produire une analyse visuelle de la performance environnementales des pays. Le projet met en contexte l'évolution de la population et du PIB afin de contextualiser les variables environnementales.

Dans cette analyse, la banque de données principale a été manipuler plusieurs fois pour obtenir de nouvelles banques permettant une analyse plus détaillée des variables.

Dans un premier temps, la banque a été changer selon les années, soit en 1955, 1975, 1995 et 2015 pour suivre l'évolution du CO2 à coup de 20 ans. Par la suite, des manipulations on été faites pour calculer le PIB par habitant et mettre cette variable en relation avec l'évolution du co2 en année. Finalement, le PIB par habitant est mis en relation avec les différent pays pour permettre la mise en place de graphiques montrant la distribution des pays selon leur PIB par habitant.

> Les données proviennent entre autres de @owiCO2
